#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 30, 2020 10:21:14 AM PDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global keep_buttons
    keep_buttons = []
    for q in range(5):
        keep_buttons.append(tk.IntVar())

def get_keepvals():
    keep = []
    for q in keep_buttons:
        keep.append(q.get()) 
    return keep

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import YahtzeeGUI
    YahtzeeGUI.vp_start_gui()




