#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 30, 2020 10:02:50 AM PDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Yahtzee_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Yahtzee_support.set_Tk_var()
    top = Toplevel1 (root)
    Yahtzee_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Yahtzee_support.set_Tk_var()
    top = Toplevel1 (w)
    Yahtzee_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("840x568+602+67")
        top.minsize(1, 1)
        top.maxsize(3505, 1170)
        top.resizable(1, 1)
        top.title("New Toplevel")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.833, rely=0.792, relheight=0.167
                , relwidth=0.119)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")

        self.Frame1_1 = tk.Frame(top)
        self.Frame1_1.place(relx=0.833, rely=0.599, relheight=0.167
                , relwidth=0.118)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")

        self.Frame1_2 = tk.Frame(top)
        self.Frame1_2.place(relx=0.833, rely=0.405, relheight=0.167
                , relwidth=0.118)
        self.Frame1_2.configure(relief='groove')
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief="groove")

        self.Frame1_3 = tk.Frame(top)
        self.Frame1_3.place(relx=0.833, rely=0.211, relheight=0.167
                , relwidth=0.118)
        self.Frame1_3.configure(relief='groove')
        self.Frame1_3.configure(borderwidth="2")
        self.Frame1_3.configure(relief="groove")

        self.Frame1_4 = tk.Frame(top)
        self.Frame1_4.place(relx=0.833, rely=0.018, relheight=0.167
                , relwidth=0.113)
        self.Frame1_4.configure(relief='groove')
        self.Frame1_4.configure(borderwidth="2")
        self.Frame1_4.configure(relief="groove")

        self.Frame1_5 = tk.Frame(top)
        self.Frame1_5.place(relx=0.929, rely=-0.511, relheight=0.167
                , relwidth=0.113)
        self.Frame1_5.configure(relief='groove')
        self.Frame1_5.configure(borderwidth="2")
        self.Frame1_5.configure(relief="groove")

        self.Checkbutton1 = tk.Checkbutton(top)
        self.Checkbutton1.place(relx=0.714, rely=0.07, relheight=0.039
                , relwidth=0.08)
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Keep''')
        self.Checkbutton1.configure(variable=Yahtzee_support.che51)

        self.Checkbutton2 = tk.Checkbutton(top)
        self.Checkbutton2.place(relx=0.714, rely=0.264, relheight=0.04
                , relwidth=0.081)
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Keep''')
        self.Checkbutton2.configure(variable=Yahtzee_support.che53)

        self.Checkbutton3 = tk.Checkbutton(top)
        self.Checkbutton3.place(relx=0.714, rely=0.458, relheight=0.04
                , relwidth=0.081)
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''Keep''')
        self.Checkbutton3.configure(variable=Yahtzee_support.che54)

        self.Checkbutton4 = tk.Checkbutton(top)
        self.Checkbutton4.place(relx=0.714, rely=0.669, relheight=0.04
                , relwidth=0.08)
        self.Checkbutton4.configure(justify='left')
        self.Checkbutton4.configure(text='''Keep''')
        self.Checkbutton4.configure(variable=Yahtzee_support.che55)

        self.Checkbutton5 = tk.Checkbutton(top)
        self.Checkbutton5.place(relx=0.726, rely=0.863, relheight=0.04
                , relwidth=0.08)
        self.Checkbutton5.configure(justify='left')
        self.Checkbutton5.configure(text='''Keep''')
        self.Checkbutton5.configure(variable=Yahtzee_support.che56)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.548, rely=0.44, height=51, width=111)
        self.Button1.configure(text='''Roll!''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.036, rely=0.123, height=21, width=84)
        self.Label1.configure(activebackground="#ffffff")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(text='''Ones''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.155, rely=0.123, height=21, width=28)
        self.Label2.configure(background="#ffffff")

        self.Label1_9 = tk.Label(top)
        self.Label1_9.place(relx=0.036, rely=0.176, height=21, width=84)
        self.Label1_9.configure(activebackground="#ffffff")
        self.Label1_9.configure(background="#ffffff")
        self.Label1_9.configure(text='''Twos''')

        self.Label2_10 = tk.Label(top)
        self.Label2_10.place(relx=0.155, rely=0.176, height=21, width=28)
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(background="#ffffff")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.202, rely=0.123, height=21, width=141)
        self.Button2.configure(text='''Score as Ones''')

        self.Button2_11 = tk.Button(top)
        self.Button2_11.place(relx=0.202, rely=0.176, height=21, width=141)
        self.Button2_11.configure(activebackground="#f9f9f9")
        self.Button2_11.configure(text='''Score as Twos''')

if __name__ == '__main__':
    vp_start_gui()





